apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "sn-chart.fullname" . }}-ingress
spec:
    rules:
    -   host: snchart.com
        http:
            paths:
                -   path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ include "sn-chart.fullname" . }}-service
                            port:
                                number: 5000