apiVersion: v1
kind: Service
metadata:
    name: {{ include "sn-chart.fullname" . }}-service
spec:
    selector:
        app: {{ include "sn-chart.fullname" . }}-sn
    ports:
    -   protocol: TCP
        port: 5000
        targetPort: 5000
